In [7]:
import numpy as np
import tensorflow as tf

a = np.array([1, 2, 3], dtype=np.int32)
t_a = tf.convert_to_tensor(a)
print(type(t_a))
print(t_a)

t_ones = tf.ones((2, 3))
print(type(t_ones))
print(t_ones)
print(t_ones.numpy())

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
print(t_a.dtype)
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)
print(t_a_new)

t_rand = tf.random.uniform(shape=(3, 5))
print(t_rand)
t_rand_transposed = tf.transpose(t_rand)
print(t_rand_transposed)

t_z = tf.zeros((30,))
print(t_z)
t_z_reshaped = tf.reshape(t_z, shape=(5, 6))
print(t_z_reshaped)

t_z2 = tf.zeros((1, 2, 1, 4, 1))
print(t_z2)
print(t_z2.shape)
t_z2_squeezed = tf.squeeze(t_z2, axis=(2, 4))
print(t_z2_squeezed)
print(t_z2_squeezed.shape)

<dtype: 'int32'>
<dtype: 'int64'>
tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor(
[[0.6854638  0.06967592 0.7433882  0.8954433  0.05743754]
 [0.6591345  0.7636764  0.983201   0.5762546  0.16247094]
 [0.8504561  0.86690414 0.95841444 0.33428752 0.6215365 ]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[0.6854638  0.6591345  0.8504561 ]
 [0.06967592 0.7636764  0.86690414]
 [0.7433882  0.983201   0.95841444]
 [0.8954433  0.5762546  0.33428752]
 [0.05743754 0.16247094 0.6215365 ]], shape=(5, 3), dtype=float32)
tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.], shape=(30,), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32)
tf.Tensor(
[[[[[0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]]]]], shape=(1, 2, 1, 4, 1), dtype=float32)
(1, 2, 1, 4, 1)
tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 2,