In [1]:
# import os
# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
import numpy as np
np.set_printoptions(precision=3)
# tf.config.threading.set_inter_op_parallelism_threads(8)

In [2]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
# Uncomment to log device usage info
# tf.debugging.set_log_device_placement(True)

In [6]:
# Create some tensors
a = tf.constant([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0],
                 [3.0, 4.0],
                 [5.0, 6.0]])
# Matric multiplication
c = tf.matmul(a, b)
a, b, c

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[22., 28.],
        [49., 64.]], dtype=float32)>)

In [4]:
a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

t_a, t_b

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>)

In [10]:
t_ones = tf.ones((2, 3))
print(t_ones.numpy())
t_ones

[[1. 1. 1.]
 [1. 1. 1.]]


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
const_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.2  , 5.   , 3.142], dtype=float32)>

In [12]:
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)
t_a_new

<dtype: 'int64'>


<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3], dtype=int64)>

In [13]:
t = tf.random.uniform(shape=(3, 5))
t_tr = tf.transpose(t)
print(t_tr.shape)
t, t_tr

(5, 3)


(<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[0.703, 0.239, 0.893, 0.267, 0.007],
        [0.252, 0.093, 0.545, 0.175, 0.047],
        [0.106, 0.295, 0.419, 0.672, 0.783]], dtype=float32)>,
 <tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[0.703, 0.252, 0.106],
        [0.239, 0.093, 0.295],
        [0.893, 0.545, 0.419],
        [0.267, 0.175, 0.672],
        [0.007, 0.047, 0.783]], dtype=float32)>)

In [14]:
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5, 6))
print(t_reshape.shape)
t, t_reshape

(5, 6)


(<tf.Tensor: shape=(30,), dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Tensor: shape=(5, 6), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], dtype=float32)>)

In [17]:
t = tf.zeros((1, 2, 1, 4, 1))
# Delete 2 and 4 dimensions (0-indexed)
t_squeezed = tf.squeeze(t, axis=(2, 4))
print(f'{t.shape} -> {t_squeezed.shape}')
t, t_squeezed

(1, 2, 1, 4, 1) -> (1, 2, 4)


(<tf.Tensor: shape=(1, 2, 1, 4, 1), dtype=float32, numpy=
 array([[[[[0.],
           [0.],
           [0.],
           [0.]]],
 
 
         [[[0.],
           [0.],
           [0.],
           [0.]]]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=float32)>)

In [19]:
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5, 2), mean=0.0, stddev=1.0)
print('t1:', t1)
print('t2:', t2)

t3 = tf.multiply(t1, t2)
print('Element wise multiplication:')
print(t3.numpy())

t4 = tf.math.reduce_mean(t1, axis=0)
print('t1 column mean:')
print(t4)

t4_sum = tf.math.reduce_sum(t1, axis=0)
print('t1 column sum:')
print(t4_sum)

t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
print('Matrix multiplication t1 * t2_transposed')
print(t5.numpy())

t6 = tf.linalg.matmul(t1, t2, transpose_a=True)
print('Matrix multiplication t1_transposed * t2')
print(t6.numpy())

t1: tf.Tensor(
[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]], shape=(5, 2), dtype=float32)
t2: tf.Tensor(
[[ 0.403 -1.088]
 [-0.063  1.337]
 [ 0.712 -0.489]
 [-0.764 -1.037]
 [-1.252  0.021]], shape=(5, 2), dtype=float32)
Element wise multiplication:
[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]
t1 column mean:
tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)
t1 column sum:
tf.Tensor([0.448 1.037], shape=(2,), dtype=float32)
Matrix multiplication t1 * t2_transposed
[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]]
Matrix multiplication t1_transposed * t2
[[-1.711  0.302]
 [ 0.371 -1.049]]


In [22]:
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t.numpy())
t_split = tf.split(t, num_or_size_splits=3)
print('Even split:')
for spl in t_split:
    print(spl)
print()
    
t = tf.random.uniform((5,))
print(t.numpy())
t_split = tf.split(t, num_or_size_splits=[3, 2])
print('Non-even split:')
for spl in t_split:
    print(spl)

[0.165 0.901 0.631 0.435 0.292 0.643]
Even split:
tf.Tensor([0.165 0.901], shape=(2,), dtype=float32)
tf.Tensor([0.631 0.435], shape=(2,), dtype=float32)
tf.Tensor([0.292 0.643], shape=(2,), dtype=float32)

[0.51  0.444 0.409 0.992 0.689]
Non-even split:
tf.Tensor([0.51  0.444 0.409], shape=(3,), dtype=float32)
tf.Tensor([0.992 0.689], shape=(2,), dtype=float32)


In [25]:
A = tf.ones((3,))
B = tf.zeros((2,))
print('A:', A)
print('B:', B)
C = tf.concat([A, B], axis=0)
print('C:', C, '\n')

A = tf.ones((3,))
B = tf.zeros((3,))
print('A:', A)
print('B:', B)
S = tf.stack([A, B], axis=0)
print('Stack axis=0:', S)
S = tf.stack([A, B], axis=1)
print('Stack axis=1:', S)

A: tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
B: tf.Tensor([0. 0.], shape=(2,), dtype=float32)
C: tf.Tensor([1. 1. 1. 0. 0.], shape=(5,), dtype=float32) 

A: tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
B: tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
Stack axis=0: tf.Tensor(
[[1. 1. 1.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
Stack axis=1: tf.Tensor(
[[1. 0.]
 [1. 0.]
 [1. 0.]], shape=(3, 2), dtype=float32)


In [27]:
a = [1.2, 3.4, 7.5, 4.1, 5.0, 1.0]
ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)

for item in ds:
    print(item)
print()
    
ds_batch = ds.batch(3)
for i, elem in enumerate(ds_batch, 1):
    print(f'batch {i}: {elem.numpy()}')

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.float32, name=None)>
tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor(4.1, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)

batch 1: [1.2 3.4 7.5]
batch 2: [4.1 5.  1. ]


In [33]:
t_x = tf.random.uniform([4, 3], dtype=tf.float32)
t_y = tf.range(4)
print('t_x:', t_x)
print('t_y:', t_y, '\n')

ds_x = tf.data.Dataset.from_tensor_slices(t_x)
print('ds_x:', ds_x)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)
print('ds_y:', ds_y)
ds_joint = tf.data.Dataset.zip((ds_x, ds_y))
for example in ds_joint:
    print(f'x: {example[0].numpy()}  y: {example[1].numpy()}')
print()

print('Alternative definition')
ds_joint = tf.data.Dataset.from_tensor_slices((t_x, t_y))
for example in ds_joint:
    print(f'x: {example[0].numpy()}  y: {example[1].numpy()}')

t_x: tf.Tensor(
[[0.298 0.963 0.429]
 [0.361 0.266 0.49 ]
 [0.253 0.312 0.965]
 [0.115 0.93  0.841]], shape=(4, 3), dtype=float32)
t_y: tf.Tensor([0 1 2 3], shape=(4,), dtype=int32) 

ds_x: <TensorSliceDataset element_spec=TensorSpec(shape=(3,), dtype=tf.float32, name=None)>
ds_y: <TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>
x: [0.298 0.963 0.429]  y: 0
x: [0.361 0.266 0.49 ]  y: 1
x: [0.253 0.312 0.965]  y: 2
x: [0.115 0.93  0.841]  y: 3

Alternative definition
x: [0.298 0.963 0.429]  y: 0
x: [0.361 0.266 0.49 ]  y: 1
x: [0.253 0.312 0.965]  y: 2
x: [0.115 0.93  0.841]  y: 3


In [34]:
ds_trans = ds_joint.map(lambda x, y: (x*2-1.0, y))
for example in ds_trans:
    print(f'x: {example[0].numpy()}  y: {example[1].numpy()}')

x: [-0.405  0.926 -0.142]  y: 0
x: [-0.279 -0.468 -0.021]  y: 1
x: [-0.493 -0.376  0.93 ]  y: 2
x: [-0.769  0.86   0.682]  y: 3


In [35]:
tf.random.set_seed(1)
ds = ds_joint.shuffle(buffer_size=len(t_x))
for example in ds:
    print(f'x: {example[0].numpy()}  y: {example[1].numpy()}')

x: [0.253 0.312 0.965]  y: 2
x: [0.361 0.266 0.49 ]  y: 1
x: [0.298 0.963 0.429]  y: 0
x: [0.115 0.93  0.841]  y: 3


In [36]:
ds = ds_joint.batch(batch_size=3, drop_remainder=False)
ds_iter = iter(ds)
batch_x, batch_y = next(ds_iter)
print('batch_x[0]:', batch_x)
print('batch_y[0]:', batch_y)
batch_x, batch_y = next(ds_iter)
print('batch_x[1]:', batch_x)
print('batch_y[1]:', batch_y)

batch_x[0]: tf.Tensor(
[[0.298 0.963 0.429]
 [0.361 0.266 0.49 ]
 [0.253 0.312 0.965]], shape=(3, 3), dtype=float32)
batch_y[0]: tf.Tensor([0 1 2], shape=(3,), dtype=int32)
batch_x[1]: tf.Tensor([[0.115 0.93  0.841]], shape=(1, 3), dtype=float32)
batch_y[1]: tf.Tensor([3], shape=(1,), dtype=int32)


In [37]:
ds = ds_joint.batch(batch_size=3).repeat(count=2)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (1, 3) [3]
2 (3, 3) [0 1 2]
3 (1, 3) [3]


In [38]:
ds = ds_joint.repeat(count=2).batch(batch_size=3)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (3, 3) [3 0 1]
2 (2, 3) [2 3]


In [39]:
tf.random.set_seed(1)
ds = ds_joint.shuffle(4).batch(batch_size=2).repeat(count=4)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (2, 3) [2 1]
1 (2, 3) [0 3]
2 (2, 3) [0 3]
3 (2, 3) [1 2]
4 (2, 3) [3 0]
5 (2, 3) [1 2]
6 (2, 3) [1 3]
7 (2, 3) [2 0]


In [40]:
tf.random.set_seed(1)
ds = ds_joint.batch(batch_size=2).shuffle(2).repeat(count=3)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (2, 3) [0 1]
1 (2, 3) [2 3]
2 (2, 3) [0 1]
3 (2, 3) [2 3]
4 (2, 3) [2 3]
5 (2, 3) [0 1]


In [41]:
tf.random.set_seed(1)
ds = ds_joint.batch(batch_size=2).repeat(count=5).shuffle(4)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (2, 3) [0 1]
1 (2, 3) [0 1]
2 (2, 3) [2 3]
3 (2, 3) [0 1]
4 (2, 3) [2 3]
5 (2, 3) [2 3]
6 (2, 3) [2 3]
7 (2, 3) [0 1]
8 (2, 3) [2 3]
9 (2, 3) [0 1]
