In [2]:
import tensorflow as tf

In [3]:
# TF 1 style
g = tf.Graph()
with g.as_default():
    a = tf.constant(1, name='a')
    b = tf.constant(2, name='b')
    c = tf.constant(3, name='c')
    z = 2*(a-b) + c

In [5]:
with tf.compat.v1.Session(graph=g) as sess:
    print('Result z =', sess.run(z))

Result z = 1


In [7]:
# TF 2 style
a = tf.constant(1, name='a')
b = tf.constant(2, name='b')
c = tf.constant(3, name='c')
z = 2*(a-b) + c
print('Result z =', z)

Result z = tf.Tensor(1, shape=(), dtype=int32)


In [9]:
# TF 1 style
g = tf.Graph()
with g.as_default():
    a = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_a')
    b = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_b')
    c = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_c')
    z = 2*(a-b) + c
    
with tf.compat.v1.Session(graph=g) as sess:
    feed_dict = {a: 1, b: 2, c: 3}
    print('Result z =', sess.run(z, feed_dict=feed_dict))

Result z = 1


In [15]:
def compute_z(a, b, c):
    r1 = tf.subtract(a, b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

In [19]:
tf.print(compute_z(1, 2, 3))
tf.print(compute_z([1], [2], [3]))
tf.print(compute_z([[1]], [[2]], [[3]]))

1
[1]
[[1]]


In [20]:
@tf.function
def compute_z(a, b, c):
    r1 = tf.subtract(a, b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

In [21]:
tf.print(compute_z(1, 2, 3))
tf.print(compute_z([1], [2], [3]))
tf.print(compute_z([[1]], [[2]], [[3]]))

1
[1]
[[1]]


In [22]:
@tf.function(input_signature=(tf.TensorSpec(shape=[None], dtype=tf.int32),
                              tf.TensorSpec(shape=[None], dtype=tf.int32),
                              tf.TensorSpec(shape=[None], dtype=tf.int32)))
def compute_z(a, b, c):
    r1 = tf.subtract(a, b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

In [26]:
tf.print(compute_z([1], [2], [3]))
tf.print(compute_z([1, 2], [2, 4], [3, 6]))
# tf.print(compute_z(1, 2, 3)) - error
# tf.print(compute_z([[1]], [[2]], [[3]])) - error

[1]
[1 2]


In [31]:
a = tf.Variable(initial_value=3.14, name='var_a')
b = tf.Variable(initial_value=[1, 2, 3], name='var_b')
c = tf.Variable(initial_value=[True, False], name='var_c')
d = tf.Variable(initial_value=['abc'], name='var_d')
(a, b, c, d)

(<tf.Variable 'var_a:0' shape=() dtype=float32, numpy=3.14>,
 <tf.Variable 'var_b:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Variable 'var_c:0' shape=(2,) dtype=bool, numpy=array([ True, False])>,
 <tf.Variable 'var_d:0' shape=(1,) dtype=string, numpy=array([b'abc'], dtype=object)>)

In [32]:
w = tf.Variable([1, 2, 3], trainable=False)
w

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

In [33]:
print(w.assign([3, 1, 4], read_value=True))
w.assign_add([2, -1, 2], read_value=False)
print(w.value())

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 1, 4])>
tf.Tensor([5 0 6], shape=(3,), dtype=int32)


In [39]:
tf.random.set_seed(1)
rand_init = tf.keras.initializers.GlorotNormal()
tf.print(rand_init(shape=(3,)))

v = tf.Variable(rand_init(shape=(2, 3)))
tf.print(v)

[1.15235567 0.281034619 -0.000759395654]
[[1.26234233 0.30785802 -0.000831876241]
 [-0.401079446 -0.464005411 0.717722535]]


In [42]:
class MyModule(tf.Module):
    def __init__(self):
        rand_init = tf.keras.initializers.GlorotNormal()
        self.w1 = tf.Variable(rand_init(shape=(2, 3)), trainable=True)
        self.w2 = tf.Variable(rand_init(shape=(1, 2)), trainable=False)
        
m = MyModule()
print('All variables:', [v.shape for v in m.variables])
print('Trainable variables:', [v.shape for v in m.trainable_variables])

All variables: [TensorShape([2, 3]), TensorShape([1, 2])]
Trainable variables: [TensorShape([2, 3])]


In [45]:
# Cannot define w inside compute_z
w = tf.Variable(tf.random.uniform((3, 3)))

@tf.function
def compute_z(x):
    return tf.matmul(w, x)

In [46]:
x = tf.constant([[1], [2], [3]], dtype=tf.float32)
tf.print(compute_z(x))

[[3.64191628]
 [1.69833195]
 [3.06276083]]
